### ISSUE TITLE
Runtime exited with error: exit status 126

### ISSUE THREAD

**Issue by bart-gcs** [micronaut-graal-tests/micronaut-function-aws-graal#1]
Steps to recreate:

1. BUILD `./build-native-image.sh`
2. DEPLOY `sam deploy -t sam-native.yaml -g`
3. TEST curl -X POST -H 'Content-Type:application/json' -d '{"category":"foo"}' https://<my-url>.amazonaws.com/Prod/jokes

Expected Results
- HTTP 200 response

Actual Results
- {"message": "Internal server error"}%  

Message In CloudWatch
- /var/task/bootstrap: line 3: ./application: cannot execute binary file
- Error: Runtime exited with error: exit status 126 Runtime.ExitError

**Comment by ilopmar** [comment]
I think the problem is in the request you send. It works with the following:

```
curl -X POST -H 'Content-Type:application/json' -d '{"micronautPackage":"bom"}' $API_ENDPOINT
```

The other one is when deploying the Joke function but at this moment we are deploying the Bintrary one: https://github.com/micronaut-graal-tests/micronaut-function-aws-graal/blob/2.3.x/build.gradle#L37


This also works in [our CI](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1002644684) so it's something on your side.
